### ISSUE TITLE
ERROR: object 'variable' not found

### ISSUE THREAD

**Issue by michbur** [michbur/shiny-density#2]
Listening on http://127.0.0.1:7005
Warning: Error in force: object 'variable' not found
Stack trace (innermost first):
    56: force
    55: restoreInput
    54: selectInput
    53: tag
    52: tags$form
    51: tag
    50: tags$div
    49: div
    48: sidebarPanel
    47: tag
    46: tags$div
    45: div
    44: tagList
    43: attachDependencies
    42: bootstrapPage
    41: fluidPage
     1: shiny::runApp
Error : object 'variable' not found

**Comment by ksidorczuk** [comment]
Removed object 'variable'. SelectInput choices are now taken from data file, not a variable.
